services:
  postgres:
    image: postgres:17.2-alpine3.20
    container_name: ${POSTGRES_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
    ports:
      - "${POSTGRES_CONTAINER_PORT}:${POSTGRES_DB_PORT}"
    # TODO:STUDY THIS (causing delay after "db is ready for connections?":
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_DB_USER} -d ${POSTGRES_DB_NAME}"]

  app:
    container_name: ${APP_CONTAINER_NAME}
    # TODO:STUDY THIS:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:${POSTGRES_DB_PORT}/${POSTGRES_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_DB_PASSWORD}
    ports:
      - "${APP_CONTAINER_PORT}:${APP_CONTAINER_PORT}"
    depends_on:
      postgres:
        condition: service_healthy