services:
  postgres:
    image: postgres:latest
    container_name: ${POSTGRES_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
    ports:
      - "${POSTGRES_CONTAINER_PORT}:${POSTGRES_DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: openjdk:23
    container_name: ${APP_CONTAINER_NAME}

    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:${POSTGRES_DB_PORT}/${POSTGRES_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_DB_PASSWORD}
    ports:
      - "${APP_CONTAINER_PORT}:${APP_CONTAINER_PORT}"

    depends_on:
      - postgres

volumes:
  postgres_data:
